### ISSUE TITLE
Fix for Gnome 42.9?

### ISSUE THREAD

**Issue by typoworx-de** [CloudyChris/multi-monitors-add-on#3]
Thanks for your fork and investigating into fixing it. I've tried on Ubuntu Jammy with Gnome 42.9 (using Wayland if that matters?) and it shows in Extension Manager, that the addon still is incompatible. Technical Details shows me this:

```
Error: No property margin on Gjs_multi-monitors-add-on_spin83_prefs_MultiMonitorsPrefsWidget

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
  _init@/home/gabriel/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/prefs.js:52:15
  MultiMonitorsPrefsWidget@/home/gabriel/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/prefs.js:50:1
  buildPrefsWidget@/home/gabriel/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/prefs.js:275:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

**Comment by typoworx-de** [comment]
I just noticed the issue is here adressed as well in the original git-source:
https://github.com/spin83/multi-monitors-add-on/issues/169

**Comment by CloudyChris** [comment]
Hi! I've had a hiatus due to having to look for work and other stuff.
I will try to look into it, but my priority right now would be making it work with gnome 45, since that's what I'm using. That being said, I'd like to support previous versions, at least all the way down to gnome 40.

**Comment by sourovafrin** [comment]
Any update on this?

**Comment by CloudyChris** [comment]
Sadly, no. I have switched to awesomewm because gnome and kde seem to hate multi-monitor setups. I will probably delete the repository since I couldn't make it work for gnome 45. Honestly, the documentation is atrocious. I can point you to a repo that's actively maintained for the extension: https://github.com/lazanet/multi-monitors-add-on
